plugins {
    id 'com.android.application'
}

android {
    namespace 'com.opendex.droiduphost'
    compileSdk 36

    defaultConfig {
        applicationId 'com.opendex.droiduphost'
        minSdk 26
        targetSdk 36
        versionCode 52
        versionName '0.5.2-droidup-fullscreen-native'
    }

    buildFeatures {
        buildConfig true
        aidl true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
    implementation 'androidx.annotation:annotation:1.9.1'
    implementation 'androidx.activity:activity:1.10.1'
}
