plugins {
    id 'com.android.application'
}

android {
    namespace 'com.opendex.launcher'
    compileSdk 37

    defaultConfig {
        applicationId 'com.opendex.launcher'
        minSdk 26
        targetSdk 37
        versionCode 30
        versionName '0.3.0-alpha'
    }

    buildFeatures {
        aidl true
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    lint {
        abortOnError true
        checkReleaseBuilds false
        disable 'QueryAllPackagesPermission'
    }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
